### ISSUE TITLE
ERROR Exception has been catch, it' a bug

### ISSUE THREAD

**Issue by yodog** [sipcapture/paStash#65]
hello.

if you need more info, let me know.

```
[Mon, 13 Jul 2020 16:28:44 GMT] ERROR Exception has been catch, it' a bug
[Mon, 13 Jul 2020 16:28:44 GMT] ERROR Please submit an issue on https://github.com/sipcapture/pastash
[Mon, 13 Jul 2020 16:28:44 GMT] ERROR Exception: TypeError: Object.entries is not a function
    at LokiPost.process (/usr/lib/node_modules/@pastash/output_loki/output_loki.js:78:33)
    at LokiPost.<anonymous> (/usr/lib/node_modules/@pastash/pastash/lib/lib/base_output.js:21:14)
    at emitOne (events.js:96:13)
    at LokiPost.emit (events.js:188:7)
    at LogstashAgent.<anonymous> (/usr/lib/node_modules/@pastash/pastash/lib/agent.js:273:14)
    at emitOne (events.js:96:13)
    at LogstashAgent.emit (events.js:188:7)
    at LogstashAgent.<anonymous> (/usr/lib/node_modules/@pastash/pastash/lib/agent.js:18:10)
    at emitOne (events.js:96:13)
    at FilterAddVersion.emit (events.js:188:7)
```
---

pastash_loki.conf

```
input {
    file {
        path => "/var/log/*.log"
    }
}

output {
    loki {
        host => "loki.my.domain"
        port => 80
        path => "/loki/api/v1/push"
    }
}
```

---

started pastash with `pastash --config_file=/root/pastash_loki.conf`

---

```
root@elastic-01:~# node -v
v6.17.1
```

**Comment by yodog** [comment]
updated node and it worked.

closing.
