### ISSUE TITLE
PgSQL output doesn't reopen connection on error threshold breach

### ISSUE THREAD

**Issue by simplevoip** [sipcapture/paStash#68]
We've been running the PgSQL output plugin for a while in production, and occasionally it attempts to insert duplicate IDs somehow. This shouldn't be a problem for our specific application, except that these primary key conflicts increase the output plugin's error count, and when the error threshold (a hard-coded >= 10) is reached, the plugin should close & reopen the connection and clear the error count.

The problem appears to be related to the node-postgres calls being made to restart that connection. Our logs end up filling up with the following error:

> Error: Client has already been connected. You cannot reuse a client.
    at Client._connect (/usr/lib/node_modules/@pastash/output_pgsql/node_modules/pg/lib/client.js:92:17)
    at /usr/lib/node_modules/@pastash/output_pgsql/node_modules/pg/lib/client.js:302:10
    at new Promise (<anonymous>)
    at Client.connect (/usr/lib/node_modules/@pastash/output_pgsql/node_modules/pg/lib/client.js:301:10)
    at Query.callback (/usr/lib/node_modules/@pastash/output_pgsql/output_pgsql.js:103:36)
    at Query.handleError (/usr/lib/node_modules/@pastash/output_pgsql/node_modules/pg/lib/query.js:138:19)
    at /usr/lib/node_modules/@pastash/output_pgsql/node_modules/pg/lib/client.js:544:13
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

It appears that we should be spinning up a `new Client()` after calling `end()` rather than attempting `pool.client.end(); pool.client.connect();`: [https://github.com/brianc/node-postgres/issues/1352](https://github.com/brianc/node-postgres/issues/1352)

**Comment by lmangani** [comment]
Good catch! So [this](https://github.com/sipcapture/paStash/blob/next/plugins/outputs/pgsql/output_pgsql.js#L103) is where it happens. Could you try replace the `pool` connect with `this.start` and see if it reconnects properly?

```
                        if(insert_failures > 10) {
				insert_failures = 0;
				logger.error("too many insert failures, restarting pool");
				pool.client.end();
				this.start();
			}
```

**Comment by simplevoip** [comment]
`3|pastash_ | TypeError: this.start is not a function`
