### ISSUE TITLE
Audiocodes Plugin: ERROR TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by NiteCrwlr** [sipcapture/paStash#95]
Hi @lmangani

I did some tests after our first conversation today, here my setup:
Audiocodes VE 7.20A.258.367
nodejs: v14.17.0
heplify-server 1.54
 
What I expect: I would like to see the traffic in Homer7 from the Audiocodes SBC between my SIP-Proxy and MS-Teams.
Is this possible?

First confusion:
https://github.com/sipcapture/paStash/wiki/Example:-AUDIOCODES-Syslog says:
"Supports 7.20A.260.012 (or lower) and 7.20A.256.511 (or higher)."
https://github.com/sipcapture/paStash/blob/next/plugins/filters/app_audiocodes/app_audiocodes.md says:
"Supports 7.20A.260.012 (or higher) and 7.20A.256.511 (or lower)."

Is my Version now supported or not?

paStash runs on the same Server as Homer7 and heplify-server, here my config (IP's changed):

```
input {
  udp {
    host => 192.168.1.100
    port => 514
    type => syslog
  }
}

filter {
  app_audiocodes{
    localip => 192.168.1.101
    autolocal => true
    localport => 5060
    debug => true
    version => '7.20A.256.511'
  }
}

output {
  if [rcinfo] != 'undefined' {
        hep {
          host => '127.0.0.1'
          port => 9060
          hep_id => 2222
        }
  }
}
```

I see many of these:

```
[Tue, 08 Jun 2021 14:08:02 GMT] ERROR TypeError: Cannot read property '1' of null
    at FilterAppAudiocodes.process (/usr/local/lib/node_modules/@pastash/filter_app_audiocodes/filter_app_audiocodes.js:103:64)
    at FilterAppAudiocodes.<anonymous> (/usr/local/lib/node_modules/@pastash/pastash/lib/lib/base_filter.js:21:24)
    at FilterAppAudiocodes.emit (events.js:376:20)
    at FilterAddVersion.<anonymous> (/usr/local/lib/node_modules/@pastash/pastash/lib/agent.js:260:14)
    at FilterAddVersion.emit (events.js:376:20)
    at FilterAddVersion.<anonymous> (/usr/local/lib/node_modules/@pastash/pastash/lib/lib/base_filter.js:27:18)
    at FilterAddVersion.emit (events.js:376:20)
    at FilterAddTimestamp.<anonymous> (/usr/local/lib/node_modules/@pastash/pastash/lib/agent.js:260:14)
    at FilterAddTimestamp.emit (events.js:376:20)
    at FilterAddTimestamp.<anonymous> (/usr/local/lib/node_modules/@pastash/pastash/lib/lib/base_filter.js:27:18)
DEBUG <134>[S=5605569] [BID=5dd74d:40]  Trace 0-4: 6bda42 GetTraceBack(+0x4b) 14a4b0b SystemError(+0x27b) 14a6219 IsrMain(+0x1f0) 7f40b5669aa1 pthread_getattr_np(+0x91) 7f40b43b5c4d hol_append(+0x2bd)  [Time:08-06@14:08:00.447]
[Tue, 08 Jun 2021 14:08:02 GMT] ERROR Exception has been catch, it' a bug
[Tue, 08 Jun 2021 14:08:02 GMT] ERROR Please submit an issue on https://github.com/sipcapture/pastash
[Tue, 08 Jun 2021 14:08:02 GMT] ERROR Exception: TypeError: Cannot read property '1' of null
```

How to debug further?

Regards

**Comment by lmangani** [comment]
Compatibility is user reported and provided.  Have you tried setting the version to `7.20A.260.012`?

**Comment by NiteCrwlr** [comment]
Yes, as I understand this is the default if the parameter "version" is not set.
I tried again with version 7.20A.260.012 and I see:

```
[Tue, 08 Jun 2021 15:20:47 GMT] ERROR Exception has been catch, it' a bug
[Tue, 08 Jun 2021 15:20:47 GMT] ERROR Please submit an issue on https://github.com/sipcapture/pastash
[Tue, 08 Jun 2021 15:20:47 GMT] ERROR Exception: TypeError: Cannot read property '1' of null
    at FilterAppAudiocodes.process (/usr/local/lib/node_modules/@pastash/filter_app_audiocodes/filter_app_audiocodes.js:104:26)
    at FilterAppAudiocodes.<anonymous> (/usr/local/lib/node_modules/@pastash/pastash/lib/lib/base_filter.js:21:24)
    at FilterAppAudiocodes.emit (events.js:376:20)
    at FilterAddVersion.<anonymous> (/usr/local/lib/node_modules/@pastash/pastash/lib/agent.js:260:14)
    at FilterAddVersion.emit (events.js:376:20)
    at FilterAddVersion.<anonymous> (/usr/local/lib/node_modules/@pastash/pastash/lib/lib/base_filter.js:27:18)
    at FilterAddVersion.emit (events.js:376:20)
    at FilterAddTimestamp.<anonymous> (/usr/local/lib/node_modules/@pastash/pastash/lib/agent.js:260:14)
    at FilterAddTimestamp.emit (events.js:376:20)
    at FilterAddTimestamp.<anonymous> (/usr/local/lib/node_modules/@pastash/pastash/lib/lib/base_filter.js:27:18)
[Tue, 08 Jun 2021 15:20:47 GMT] ERROR TypeError: Cannot read property '1' of null
    at FilterAppAudiocodes.process (/usr/local/lib/node_modules/@pastash/filter_app_audiocodes/filter_app_audiocodes.js:104:26)
    at FilterAppAudiocodes.<anonymous> (/usr/local/lib/node_modules/@pastash/pastash/lib/lib/base_filter.js:21:24)
    at FilterAppAudiocodes.emit (events.js:376:20)
    at FilterAddVersion.<anonymous> (/usr/local/lib/node_modules/@pastash/pastash/lib/agent.js:260:14)
    at FilterAddVersion.emit (events.js:376:20)
    at FilterAddVersion.<anonymous> (/usr/local/lib/node_modules/@pastash/pastash/lib/lib/base_filter.js:27:18)
    at FilterAddVersion.emit (events.js:376:20)
    at FilterAddTimestamp.<anonymous> (/usr/local/lib/node_modules/@pastash/pastash/lib/agent.js:260:14)
    at FilterAddTimestamp.emit (events.js:376:20)
    at FilterAddTimestamp.<anonymous> (/usr/local/lib/node_modules/@pastash/pastash/lib/lib/base_filter.js:27:18)
[Tue, 08 Jun 2021 15:20:47 GMT] ERROR failed parsing Outgoing SIP. Cache on!
```

I don't know how to dig deeper into this. Just let me know if I can help.
Btw. 720A.258 is the recommended version by Microsoft for MS-Teams direct routing, so I'm not able to change. 
https://docs.microsoft.com/en-us/microsoftteams/direct-routing-border-controllers

**Comment by lmangani** [comment]
Perhaps the other audiocoders on the group here can comment, but I'm afraid we'll need some samples of your data to even imagine what might be wrong. 

In any other case, If you'd like to take this forward and have a bit of time and patience for trial & error, go ahead and create an alternate recipe similar to the following to dump some raw logs from the syslog causing the crash:

```
input {
  udp {
    host => 0.0.0.0
    port => 514
    type => syslog
  }
}

output {
    file {
      path => "/tmp/audiocodes.log"
    }
}
```

Dump some data into the system - sanitize if needed - and share it back for us to take a look at the format. No promises.

**Comment by NiteCrwlr** [comment]
Dear @lmangani: I created a syslog-recording of a call directly from the SBC, you can have a look at this with a helpful tool from audiocodes:
http://redirect.audiocodes.com/install/index.html

If you click on the Symbol "i", you can see the call flow.
I hope this helps, perhaps you can throw this log to pastash?

Please find the sanitized log attached.
[pastash_debugcall_syslogviewer_sanitized.txt](https://github.com/sipcapture/paStash/files/6653801/pastash_debugcall_syslogviewer_sanitized.txt)

**Comment by joeireland** [comment]
Is there any progress on this issue? I'm also seeing the exact same exception. I'm running version 7.40A.005.306 and have the following configuration settings.

```
input {
  udp {
    host => 0.0.0.0
    port => 514
    type => syslog
  }
}

filter {
  app_audiocodes {
    autolocal => false
    localip => 10.1.2.4
    localport => 5061
    qos => true
    debug => true
  }
}

output {
  stdout{}
  if [rcinfo] != 'undefined' {
    hep {
      host => '10.1.2.4'
      port => 9060
      hep_id => 2222
      hep_type => 1
    }
  }
}
```

Here's the DEBUG output as well as the thrown exception

```
DEBUG <157>[S=103896] [SID=1d8f27:15:2031682]  (N  9932561) ---- Incoming SIP Message from 207.35.173.122:49118 to SIPInterface #1 (Incoming) TLS TO(#1727) SocketID(57466) ----
SIP/2.0 200 OK
Via: SIP/2.0/TLS 52.188.205.180:5081;alias;branch=z9hG4bKac1973126661
From: <sip:F8-DC-7A-06-68-0C-control@52.188.205.180>;tag=1c525271332
To: <sip:F8-DC-7A-06-68-0C-control@52.188.205.180>;tag=547681347
Call-ID: 8678596315820211652@52.188.205.180
CSeq: 1 MESSAGE
User-Agent: antisip/5.2.1-502-gbe145835-Jul-13-2021 amdroid/0.1
Content-Length: 0


(N  9932562) SIPLadder::FillVQMData not generated
(N  9932563) AcSIPDialog(#8469): Handling 200 OK in state DialogInitiated
(N  9932564) States: (#8469)AcSIPDialog[DialogInitiated->DialogConnected]
(N  9932565) SBCGeneralResponseData: (#1239)AcSBCDialogAPI -> (#1239)SIPSBCDialogLeg
(N  9932566) AcSIPDialog(#8469): Handling DIALOG_DISCONNECT_REQ in state DialogConnected
(N  9932567) States: (#8469)AcSIPDialog[DialogConnected->DialogDisconnected]
        (#8469)AcSIPDialog[Deallocated]
        (#8469)AcSIPDialog[DialogDisconnected->DialogIdle]
(N  9932568) RELEASE_EV: (#1239)SIPSBCDialogLeg -> (#1289)SBCDialog[Initiated->Disconnecting]
        -> (#2216)CallPlacement
 [Time:15-08@01:06:52.884]
[Sun, 15 Aug 2021 01:06:55 GMT] ERROR Exception has been catch, it' a bug
[Sun, 15 Aug 2021 01:06:55 GMT] ERROR Please submit an issue on https://github.com/sipcapture/pastash
[Sun, 15 Aug 2021 01:06:55 GMT] ERROR Exception: TypeError: Cannot read property '1' of null
    at FilterAppAudiocodes.process (/usr/local/lib/node_modules/@pastash/filter_app_audiocodes/filter_app_audiocodes.js:103:64)
    at FilterAppAudiocodes.<anonymous> (/usr/local/lib/node_modules/@pastash/pastash/lib/lib/base_filter.js:21:24)
    at FilterAppAudiocodes.emit (events.js:314:20)
    at FilterAddVersion.<anonymous> (/usr/local/lib/node_modules/@pastash/pastash/lib/agent.js:260:14)
    at FilterAddVersion.emit (events.js:314:20)
    at FilterAddVersion.<anonymous> (/usr/local/lib/node_modules/@pastash/pastash/lib/lib/base_filter.js:27:18)
    at FilterAddVersion.emit (events.js:314:20)
    at FilterAddTimestamp.<anonymous> (/usr/local/lib/node_modules/@pastash/pastash/lib/agent.js:260:14)
    at FilterAddTimestamp.emit (events.js:314:20)
    at FilterAddTimestamp.<anonymous> (/usr/local/lib/node_modules/@pastash/pastash/lib/lib/base_filter.js:27:18)
[Sun, 15 Aug 2021 01:06:55 GMT] ERROR TypeError: Cannot read property '1' of null
    at FilterAppAudiocodes.process (/usr/local/lib/node_modules/@pastash/filter_app_audiocodes/filter_app_audiocodes.js:103:64)
    at FilterAppAudiocodes.<anonymous> (/usr/local/lib/node_modules/@pastash/pastash/lib/lib/base_filter.js:21:24)
    at FilterAppAudiocodes.emit (events.js:314:20)
    at FilterAddVersion.<anonymous> (/usr/local/lib/node_modules/@pastash/pastash/lib/agent.js:260:14)
    at FilterAddVersion.emit (events.js:314:20)
    at FilterAddVersion.<anonymous> (/usr/local/lib/node_modules/@pastash/pastash/lib/lib/base_filter.js:27:18)
    at FilterAddVersion.emit (events.js:314:20)
    at FilterAddTimestamp.<anonymous> (/usr/local/lib/node_modules/@pastash/pastash/lib/agent.js:260:14)
    at FilterAddTimestamp.emit (events.js:314:20)
    at FilterAddTimestamp.<anonymous> (/usr/local/lib/node_modules/@pastash/pastash/lib/lib/base_filter.js:27:18)
```

**Comment by NiteCrwlr** [comment]
I did not make any progress. I'm not a programmer and I'm hoping for a pointer where to dig deeper into this issue.
